name: Create AWS ECR repository
description: Creates AWS ECR repository if not available
branding:
  icon: sun
  color: red
inputs:
  ecr-name:
    description: >
      Name of repository that will be created if not already exists.
      If not provided then name of git repository where action is executed is used.
    required: false
outputs:
  ecr-name:
    description: The name of the ECR repository. Same as `ecr-name` in inputs.
  ecr-arn:
    description: The ARN of the ECR repository.
  ecr-uri:
    description: The URI of the ECR repository.
runs:
  using: node12
  main: lib/index.js
